# Generated by Django 2.1.1 on 2019-01-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/image', verbose_name='Фото новости')),
                ('text', models.TextField(verbose_name='Текс новости')),
            ],
        ),
    ]
