# Generated by Django 2.1.5 on 2019-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_list', '0002_auto_20190116_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
