# Generated by Django 2.1.1 on 2019-01-17 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers_list', '0003_auto_20190116_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='password',
        ),
        migrations.AlterField(
            model_name='workers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин'),
        ),
    ]
