# Generated by Django 2.1.1 on 2019-01-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_list', '0004_auto_20190117_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='image',
            field=models.ImageField(blank=True, default='workers_list/photos/default_user.jpg', upload_to='workers_list/photos', verbose_name='Фото сотрудника'),
        ),
    ]
