# Generated by Django 2.1.1 on 2019-01-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers_list', '0005_auto_20190119_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
